name = "twi-research-center"
pages_build_output_dir = "."
compatibility_date = "2026-03-26"

[[d1_databases]]
binding = "DB"
database_name = "sp1e-db"
database_id = "6452c73c-7d9a-487e-bffc-15c8ebfe202e"

[[r2_buckets]]
binding = "FILES"
bucket_name = "sp1e-files"

[[services]]
binding = "TWI_ORCHESTRATOR"
service = "twi-orchestrator"

[vars]
TWI_LYRIA_ESTIMATE_USD = ""

